/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaquetesRouteImport } from './routes/paquetes'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ComprasEstadoRouteImport } from './routes/compras/estado'
import { Route as AuthenticatedComprasIndexRouteImport } from './routes/_authenticated/compras/index'
import { Route as AuthenticatedEstudiosIndexRouteImport } from './routes/_authenticated/estudios/index'
import { Route as AuthenticatedEstudiosCartaNatalRouteImport } from './routes/_authenticated/estudios/carta-natal'
import { Route as AuthenticatedEstudiosHistorialRouteImport } from './routes/_authenticated/estudios/historial'
import { Route as AuthenticatedEstudiosRevolucionSolarRouteImport } from './routes/_authenticated/estudios/revolucion-solar'
import { Route as AuthenticatedEstudiosSinastriaRouteImport } from './routes/_authenticated/estudios/sinastria'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedEstudiosResultadoIdRouteImport } from './routes/_authenticated/estudios/resultado.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaquetesRoute = PaquetesRouteImport.update({
  id: '/paquetes',
  path: '/paquetes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ComprasEstadoRoute = ComprasEstadoRouteImport.update({
  id: '/compras/estado',
  path: '/compras/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComprasIndexRoute =
  AuthenticatedComprasIndexRouteImport.update({
    id: '/compras/',
    path: '/compras/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudiosIndexRoute =
  AuthenticatedEstudiosIndexRouteImport.update({
    id: '/estudios/',
    path: '/estudios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudiosCartaNatalRoute =
  AuthenticatedEstudiosCartaNatalRouteImport.update({
    id: '/estudios/carta-natal',
    path: '/estudios/carta-natal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudiosHistorialRoute =
  AuthenticatedEstudiosHistorialRouteImport.update({
    id: '/estudios/historial',
    path: '/estudios/historial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudiosRevolucionSolarRoute =
  AuthenticatedEstudiosRevolucionSolarRouteImport.update({
    id: '/estudios/revolucion-solar',
    path: '/estudios/revolucion-solar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudiosSinastriaRoute =
  AuthenticatedEstudiosSinastriaRouteImport.update({
    id: '/estudios/sinastria',
    path: '/estudios/sinastria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstudiosResultadoIdRoute =
  AuthenticatedEstudiosResultadoIdRouteImport.update({
    id: '/estudios/resultado/$id',
    path: '/estudios/resultado/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/paquetes': typeof PaquetesRoute
  '/registro': typeof RegistroRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/compras/estado': typeof ComprasEstadoRoute
  '/estudios/carta-natal': typeof AuthenticatedEstudiosCartaNatalRoute
  '/estudios/historial': typeof AuthenticatedEstudiosHistorialRoute
  '/estudios/revolucion-solar': typeof AuthenticatedEstudiosRevolucionSolarRoute
  '/estudios/sinastria': typeof AuthenticatedEstudiosSinastriaRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/compras/': typeof AuthenticatedComprasIndexRoute
  '/estudios/': typeof AuthenticatedEstudiosIndexRoute
  '/estudios/resultado/$id': typeof AuthenticatedEstudiosResultadoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/paquetes': typeof PaquetesRoute
  '/registro': typeof RegistroRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/compras/estado': typeof ComprasEstadoRoute
  '/estudios/carta-natal': typeof AuthenticatedEstudiosCartaNatalRoute
  '/estudios/historial': typeof AuthenticatedEstudiosHistorialRoute
  '/estudios/revolucion-solar': typeof AuthenticatedEstudiosRevolucionSolarRoute
  '/estudios/sinastria': typeof AuthenticatedEstudiosSinastriaRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/compras': typeof AuthenticatedComprasIndexRoute
  '/estudios': typeof AuthenticatedEstudiosIndexRoute
  '/estudios/resultado/$id': typeof AuthenticatedEstudiosResultadoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/paquetes': typeof PaquetesRoute
  '/registro': typeof RegistroRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/compras/estado': typeof ComprasEstadoRoute
  '/_authenticated/estudios/carta-natal': typeof AuthenticatedEstudiosCartaNatalRoute
  '/_authenticated/estudios/historial': typeof AuthenticatedEstudiosHistorialRoute
  '/_authenticated/estudios/revolucion-solar': typeof AuthenticatedEstudiosRevolucionSolarRoute
  '/_authenticated/estudios/sinastria': typeof AuthenticatedEstudiosSinastriaRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/compras/': typeof AuthenticatedComprasIndexRoute
  '/_authenticated/estudios/': typeof AuthenticatedEstudiosIndexRoute
  '/_authenticated/estudios/resultado/$id': typeof AuthenticatedEstudiosResultadoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/paquetes'
    | '/registro'
    | '/dashboard'
    | '/compras/estado'
    | '/estudios/carta-natal'
    | '/estudios/historial'
    | '/estudios/revolucion-solar'
    | '/estudios/sinastria'
    | '/api/public/stripe-webhook'
    | '/compras/'
    | '/estudios/'
    | '/estudios/resultado/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/paquetes'
    | '/registro'
    | '/dashboard'
    | '/compras/estado'
    | '/estudios/carta-natal'
    | '/estudios/historial'
    | '/estudios/revolucion-solar'
    | '/estudios/sinastria'
    | '/api/public/stripe-webhook'
    | '/compras'
    | '/estudios'
    | '/estudios/resultado/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/paquetes'
    | '/registro'
    | '/_authenticated/dashboard'
    | '/compras/estado'
    | '/_authenticated/estudios/carta-natal'
    | '/_authenticated/estudios/historial'
    | '/_authenticated/estudios/revolucion-solar'
    | '/_authenticated/estudios/sinastria'
    | '/api/public/stripe-webhook'
    | '/_authenticated/compras/'
    | '/_authenticated/estudios/'
    | '/_authenticated/estudios/resultado/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaquetesRoute: typeof PaquetesRoute
  RegistroRoute: typeof RegistroRoute
  ComprasEstadoRoute: typeof ComprasEstadoRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paquetes': {
      id: '/paquetes'
      path: '/paquetes'
      fullPath: '/paquetes'
      preLoaderRoute: typeof PaquetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/compras/estado': {
      id: '/compras/estado'
      path: '/compras/estado'
      fullPath: '/compras/estado'
      preLoaderRoute: typeof ComprasEstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compras/': {
      id: '/_authenticated/compras/'
      path: '/compras'
      fullPath: '/compras/'
      preLoaderRoute: typeof AuthenticatedComprasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudios/': {
      id: '/_authenticated/estudios/'
      path: '/estudios'
      fullPath: '/estudios/'
      preLoaderRoute: typeof AuthenticatedEstudiosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudios/carta-natal': {
      id: '/_authenticated/estudios/carta-natal'
      path: '/estudios/carta-natal'
      fullPath: '/estudios/carta-natal'
      preLoaderRoute: typeof AuthenticatedEstudiosCartaNatalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudios/historial': {
      id: '/_authenticated/estudios/historial'
      path: '/estudios/historial'
      fullPath: '/estudios/historial'
      preLoaderRoute: typeof AuthenticatedEstudiosHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudios/revolucion-solar': {
      id: '/_authenticated/estudios/revolucion-solar'
      path: '/estudios/revolucion-solar'
      fullPath: '/estudios/revolucion-solar'
      preLoaderRoute: typeof AuthenticatedEstudiosRevolucionSolarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudios/sinastria': {
      id: '/_authenticated/estudios/sinastria'
      path: '/estudios/sinastria'
      fullPath: '/estudios/sinastria'
      preLoaderRoute: typeof AuthenticatedEstudiosSinastriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estudios/resultado/$id': {
      id: '/_authenticated/estudios/resultado/$id'
      path: '/estudios/resultado/$id'
      fullPath: '/estudios/resultado/$id'
      preLoaderRoute: typeof AuthenticatedEstudiosResultadoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstudiosCartaNatalRoute: typeof AuthenticatedEstudiosCartaNatalRoute
  AuthenticatedEstudiosHistorialRoute: typeof AuthenticatedEstudiosHistorialRoute
  AuthenticatedEstudiosRevolucionSolarRoute: typeof AuthenticatedEstudiosRevolucionSolarRoute
  AuthenticatedEstudiosSinastriaRoute: typeof AuthenticatedEstudiosSinastriaRoute
  AuthenticatedComprasIndexRoute: typeof AuthenticatedComprasIndexRoute
  AuthenticatedEstudiosIndexRoute: typeof AuthenticatedEstudiosIndexRoute
  AuthenticatedEstudiosResultadoIdRoute: typeof AuthenticatedEstudiosResultadoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstudiosCartaNatalRoute: AuthenticatedEstudiosCartaNatalRoute,
  AuthenticatedEstudiosHistorialRoute: AuthenticatedEstudiosHistorialRoute,
  AuthenticatedEstudiosRevolucionSolarRoute:
    AuthenticatedEstudiosRevolucionSolarRoute,
  AuthenticatedEstudiosSinastriaRoute: AuthenticatedEstudiosSinastriaRoute,
  AuthenticatedComprasIndexRoute: AuthenticatedComprasIndexRoute,
  AuthenticatedEstudiosIndexRoute: AuthenticatedEstudiosIndexRoute,
  AuthenticatedEstudiosResultadoIdRoute: AuthenticatedEstudiosResultadoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PaquetesRoute: PaquetesRoute,
  RegistroRoute: RegistroRoute,
  ComprasEstadoRoute: ComprasEstadoRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
